language: node_js

sudo: false

node_js:
  - 6

script: npm test

deploy:
  provider: npm
  email: support@mangopay.com
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: false
    branch: travis
    repo: Mangopay/cardregistration-js-kit