language: node_js
node_js:
- 6
script: npm test
deploy:
  provider: npm
  email: support@mangopay.com
  api_key:
    secure: $NPM_TOKEN
  on:
    repo: Mangopay/cardregistration-js-kit
    branch: travis
