language: node_js

node_js:
  - "6"

script: npm test

before_install:
  - "npm install -g npm@latest"

deploy:
  provider: npm
  email: support@mangopay.com
  api_key: $NPM_TOKEN
  on:
    tags: false
    branch: travis