language: node_js

node_js:
  - 4

script: npm test

deploy:
  provider: npm
  email: support@mangopay.com
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    branch: travis
    repo: Mangopay/cardregistration-js-kit