language: node_js

sudo: false

node_js:
  - 0.12.7

install:
- npm cache clean
- npm install -g npm@latest
- npm update
- npm install

script: npm test

deploy:
  provider: npm
  email: support@mangopay.com
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: false
    branch: travis
    repo: Mangopay/cardregistration-js-kit