language: node_js

sudo: false

node_js:
  - stable

script: npm test

before_install:
  - "npm install -g npm@latest"

deploy:
  provider: npm
  email: support@mangopay.com
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: false
    branch: travis
    repo: Mangopay/cardregistration-js-kit