language: node_js

sudo: false

node_js:
  - 0.12.7

script: npm test

before_install:
  - npm i -g makeshift && makeshift -s @Mangopay -r https://registry.npmjs.org

deploy:
  provider: npm
  email: support@mangopay.com
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: false
    branch: travis
    repo: Mangopay/cardregistration-js-kit